pipeline {
  agent any

  environment {
    CI = 'true'
    DIND_HOST = 'tcp://172.19.0.3:2375'
  }

  stages {
    stage('Build') {
      steps {
        sh '''
          set -e
          tar -czf - . | \
          DOCKER_HOST=$DIND_HOST DOCKER_TLS_VERIFY= DOCKER_CERT_PATH= DOCKER_TLS_CERTDIR= \
          docker run --rm -i \
            -e CI=true \
            -w /work \
            node:lts-buster-slim \
            bash -lc "mkdir -p /work && tar -xzf - -C /work && npm install"
        '''
      }
    }

    stage('Test') {
      steps {
        sh '''
          set -e
          tar -czf - . | \
          DOCKER_HOST=$DIND_HOST DOCKER_TLS_VERIFY= DOCKER_CERT_PATH= DOCKER_TLS_CERTDIR= \
          docker run --rm -i \
            -e CI=true \
            -w /work \
            node:lts-buster-slim \
            bash -lc "mkdir -p /work && tar -xzf - -C /work && CI=true npm test -- --watchAll=false"
        '''
      }
    }

    stage('Manual Approval') {
      steps {
        script {
          input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
        }
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          set -e
          export DOCKER_HOST=$DIND_HOST
          export DOCKER_TLS_VERIFY=
          export DOCKER_CERT_PATH=
          export DOCKER_TLS_CERTDIR=

          ./jenkins/scripts/deliver.sh
          sleep 60
          ./jenkins/scripts/kill.sh
        '''
      }
    }
  }
}
