pipeline {
  agent any

  environment {
    CI = 'true'
  }

  stages {
    stage('Build') {
      steps {
        sh '''
          docker run --rm \
            -e CI=true \
            -v "$WORKSPACE:/work" -w /work \
            node:lts-buster-slim \
            bash -lc "npm install"
        '''
      }
    }

    stage('Test') {
      steps {
        sh '''
          docker run --rm \
            -e CI=true \
            -v "$WORKSPACE:/work" -w /work \
            node:lts-buster-slim \
            bash -lc "CI=true npm test -- --watchAll=false"
        '''
      }
    }

    stage('Manual Approval') {
      steps {
        input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
      }
    }

    stage('Deploy') {
      steps {
        sh '''
          docker build -t react-app-image .
          docker rm -f react-app 2>/dev/null || true
          docker run -d --name react-app -p 3000:3000 react-app-image

          sleep 60

          docker stop react-app 2>/dev/null || true
          docker rm -f react-app 2>/dev/null || true
          exit 0
        '''
      }
    }
  }
}
